name: Deploy Release

on:
  push:
    branches:
      - master

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: npm install
      run: npm install
    - name: npm run prettier
      run: npm run prettier
    - name: npm run lint
      run: npm run lint
    - name: npm run build
      run: npm run build-all
    - name: npm run test
      run: npm run test
